package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'base',
    srcs = [
    ],
    deps = [
        '//thirdlibs/glog:glog',
        '//thirdlibs/gflags:gflags',
    ],
    hdrs = glob(['*.h']),
)

